[project]
name = "lego-duck-race"
version = "0.1.0"
description = "Interface code for Brickworld 2025 Lego Duck Race Project"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "adafruit-circuitpython-neopixel==6.3.18",
    "buildhat==0.9.0",
    "gpiozero==2.0.1",
    "hidapi==0.14.0.post4",
]

[dependency-groups]
dev = [
    "ruff>=0.14.3",
]
