name: Build and Test Lego Duck Race

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        # This is the version of the action for setting up Python, not the Python version.
        uses: actions/setup-python@v6
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.14'
      # Install uv build system
      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install dependencies
        run: uv sync --locked --all-extras --dev
  linter:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Ruff linter
        run: uv run ruff check --output-format=github
  tests:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Tests
        run: uv run pytest
